//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.08 at 12:39:45 PM CEST 
//


package packagee;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="unit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="g"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="EL"/>
 *     &lt;enumeration value="Pck."/>
 *     &lt;enumeration value="Stk."/>
 *     &lt;enumeration value="Tasse"/>
 *     &lt;enumeration value="Scheibe"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "unit")
@XmlEnum
public enum Unit {

    @XmlEnumValue("g")
    G("g"),
    TL("TL"),
    EL("EL"),
    @XmlEnumValue("Pck.")
    PCK("Pck."),
    @XmlEnumValue("Stk.")
    STK("Stk."),
    @XmlEnumValue("Tasse")
    TASSE("Tasse"),
    @XmlEnumValue("Scheibe")
    SCHEIBE("Scheibe");
    private final String value;

    Unit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Unit fromValue(String v) {
        for (Unit c: Unit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
