//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.06 at 11:47:12 PM CEST 
//


package com.w3schools;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.w3schools package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Schritte_QNAME = new QName("http://www.w3schools.com", "schritte");
    private final static QName _Schritt_QNAME = new QName("http://www.w3schools.com", "schritt");
    private final static QName _Zutaten_QNAME = new QName("http://www.w3schools.com", "zutaten");
    private final static QName _Zutat_QNAME = new QName("http://www.w3schools.com", "zutat");
    private final static QName _Chefkochbuch_QNAME = new QName("http://www.w3schools.com", "chefkochbuch");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.w3schools
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchritteTyp }
     * 
     */
    public SchritteTyp createSchritteTyp() {
        return new SchritteTyp();
    }

    /**
     * Create an instance of {@link Rezept }
     * 
     */
    public Rezept createRezept() {
        return new Rezept();
    }

    /**
     * Create an instance of {@link ZutatenTyp }
     * 
     */
    public ZutatenTyp createZutatenTyp() {
        return new ZutatenTyp();
    }

    /**
     * Create an instance of {@link ZutatTyp }
     * 
     */
    public ZutatTyp createZutatTyp() {
        return new ZutatTyp();
    }

    /**
     * Create an instance of {@link KochbuchTyp }
     * 
     */
    public KochbuchTyp createKochbuchTyp() {
        return new KochbuchTyp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchritteTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3schools.com", name = "schritte")
    public JAXBElement<SchritteTyp> createSchritte(SchritteTyp value) {
        return new JAXBElement<SchritteTyp>(_Schritte_QNAME, SchritteTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3schools.com", name = "schritt")
    public JAXBElement<String> createSchritt(String value) {
        return new JAXBElement<String>(_Schritt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZutatenTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3schools.com", name = "zutaten")
    public JAXBElement<ZutatenTyp> createZutaten(ZutatenTyp value) {
        return new JAXBElement<ZutatenTyp>(_Zutaten_QNAME, ZutatenTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZutatTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3schools.com", name = "zutat")
    public JAXBElement<ZutatTyp> createZutat(ZutatTyp value) {
        return new JAXBElement<ZutatTyp>(_Zutat_QNAME, ZutatTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KochbuchTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3schools.com", name = "chefkochbuch")
    public JAXBElement<KochbuchTyp> createChefkochbuch(KochbuchTyp value) {
        return new JAXBElement<KochbuchTyp>(_Chefkochbuch_QNAME, KochbuchTyp.class, null, value);
    }

}
